# Generated by Django 5.1.3 on 2024-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='kaspi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
