# Generated by Django 5.1.3 on 2024-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_is_paid_ad_kaspi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('technics', 'Техника'), ('clothes', 'Одежда'), ('services', 'Услуги'), ('trend', 'Тренд'), ('tickets and others', 'Билеты и другое')], default='tickets and others', max_length=50),
        ),
    ]
