# Generated by Django 5.1.3 on 2024-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_options_alter_ad_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp номер'),
        ),
    ]
